### PR TITLE
My Contribution

### PR DESCRIPTION
**Pull request by ruqaiyasattar**
I have forked, cloned, added the new branch named "mytask", and made changes by creating Applicant's contribution folder with the "Ruqaiya_Sattar" folder within every task. Please review and let me know any changes

### CODE REVIEW

**Comment by jafsia** [comment]
The technical documentation is quite rich and extensive. Tasks 0 and 1 have been executed with mastery. I wish you had used a tool like FIGMA for UX/UI. Still, I appreciate the quality of the research. Great job

**Comment by ruqaiyasattar** [comment]
> The technical documentation is quite rich and extensive. Tasks 0 and 1 have been executed with mastery. I wish you had used a tool like FIGMA for UX/UI. Still, I appreciate the quality of the research. Great job

Thank you so much, Sir! designing a prototype via FIGMA was not clearly mentioned in Task2, so I just focused on research!  Can I still make the UI/UX design and send PR before the deadline?

**Comment by jafsia** [comment]
Yes

**Comment by ruqaiyasattar** [comment]
Sir I have few questions to ask..
1) how you decide which applicant to accept as an intern? As there are alot
if contributions going on


2) internship project timeline will be shared by me or can you share me
what work tasks are expected to work-on by me within internship round
If you share me tasks list then i can make my timeline accordingly

**Pull request merged**
